import type { Metadata } from "next";
import { IBM_Plex_Sans, Inter } from "next/font/google";

import "./globals.css";
import { fetchCoffeeStores } from "@/libs/coffee-stores-api";

const ibmSans = IBM_Plex_Sans({
  display: "swap",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-ibmplexsans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getData() {
  return await fetchCoffeeStores();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const coffeeShops = await getData();
  return (
    <html lang="en">
      <body className={`${ibmSans.className}`}>{children}</body>
    </html>
  );
}
